import jsPDF from 'jspdf';

/**
 * Generate and download PDF for itinerary plan
 */
export const downloadItineraryPDF = (itinerary) => {
  try {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    let yPosition = 20;
    const margin = 20;
    const lineHeight = 7;
    const maxWidth = pageWidth - 2 * margin;

    // Helper function to add new page if needed
    const checkNewPage = (requiredSpace = 20) => {
      if (yPosition + requiredSpace > pageHeight - margin) {
        doc.addPage();
        yPosition = 20;
        return true;
      }
      return false;
    };

    // Title
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('Trip Itinerary', margin, yPosition);
    yPosition += 10;

    // Destination and dates
    doc.setFontSize(14);
    doc.setFont('helvetica', 'normal');
    if (itinerary.destination) {
      doc.text(`Destination: ${itinerary.destination}`, margin, yPosition);
      yPosition += lineHeight;
    }
    if (itinerary.startDate && itinerary.endDate) {
      const startDate = new Date(itinerary.startDate).toLocaleDateString();
      const endDate = new Date(itinerary.endDate).toLocaleDateString();
      doc.text(`Dates: ${startDate} - ${endDate}`, margin, yPosition);
      yPosition += lineHeight;
    }
    if (itinerary.budget) {
      doc.text(`Budget: ${itinerary.budget}`, margin, yPosition);
      yPosition += lineHeight;
    }

    yPosition += 5;

    // Days and activities
    const days = itinerary.days || itinerary.itinerary || [];
    
    days.forEach((day, dayIndex) => {
      checkNewPage(30);
      
      // Day header
      doc.setFontSize(16);
      doc.setFont('helvetica', 'bold');
      const dayText = `Day ${day.dayNumber || dayIndex + 1}`;
      if (day.date) {
        const dateStr = new Date(day.date).toLocaleDateString('en-US', { 
          weekday: 'long', 
          month: 'long', 
          day: 'numeric' 
        });
        doc.text(`${dayText} - ${dateStr}`, margin, yPosition);
      } else {
        doc.text(dayText, margin, yPosition);
      }
      yPosition += lineHeight + 2;

      // Activities
      const activities = day.activities || [];
      activities.forEach((activity, actIndex) => {
        checkNewPage(15);

        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        
        // Time and activity name
        const timeText = activity.time || '';
        const activityText = activity.activity || activity.name || 'Activity';
        doc.text(`${timeText} - ${activityText}`, margin + 5, yPosition);
        yPosition += lineHeight;

        // Location
        if (activity.location) {
          doc.setFontSize(10);
          doc.setFont('helvetica', 'italic');
          doc.setTextColor(100, 100, 100);
          doc.text(`📍 ${activity.location}`, margin + 10, yPosition);
          yPosition += lineHeight;
          doc.setTextColor(0, 0, 0);
        }

        // Notes/Description
        if (activity.notes || activity.description) {
          doc.setFontSize(10);
          doc.setFont('helvetica', 'normal');
          const notes = (activity.notes || activity.description || '').substring(0, 100);
          const splitNotes = doc.splitTextToSize(notes, maxWidth - 15);
          doc.text(splitNotes, margin + 10, yPosition);
          yPosition += splitNotes.length * lineHeight;
        }

        yPosition += 3;
      });

      yPosition += 5;
    });

    // Footer
    const totalPages = doc.internal.pages.length - 1;
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(
        `Generated by GoPlanner - Page ${i} of ${totalPages}`,
        pageWidth / 2,
        pageHeight - 10,
        { align: 'center' }
      );
      doc.setTextColor(0, 0, 0);
    }

    // Download PDF
    const fileName = `GoPlanner_${itinerary.destination || 'Trip'}_${new Date().toISOString().split('T')[0]}.pdf`;
    doc.save(fileName);
    
    return { success: true };
  } catch (error) {
    console.error('Error generating PDF:', error);
    return { success: false, error: error.message };
  }
};

